In [1]:
import pandas as pd
import numpy as np

In [27]:
file = '/Users/meruozhu/Downloads/MP_data/MP_codes/MP/Data/synthetic_dataset/IOR5000.csv'
data = pd.read_csv(file, low_memory=False)

In [28]:
data.iloc[[5,100,201,245],:]

,case,event,startTime,completeTime,LogType,org:resource
5,b1_113,Assess eligibility,2004/02/11 19:30:07.055,2004/02/11 19:30:07.055,MXML.EnactmentLog,NaN
100,b1_51,Assess loan risk,2004/02/05 19:43:08.092,2004/02/05 19:43:08.092,MXML.EnactmentLog,NaN
201,b1_388,Check credit history,2004/03/05 20:34:00.185,2004/03/05 20:34:00.185,MXML.EnactmentLog,NaN
245,b1_366,Send home insurance quote,2004/03/04 23:45:28.894,2004/03/04 23:45:28.894,MXML.EnactmentLog,NaN

In [13]:
data = data.iloc[:6, :]

In [14]:
data

,case,event,startTime,completeTime,LogType,org:resource
0,b1_113,Loan application received,2004/02/11 17:30:00.000,2004/02/11 17:30:00.000,MXML.EnactmentLog,NaN
1,b1_113,Check application form completeness,2004/02/11 17:55:28.917,2004/02/11 17:55:28.917,MXML.EnactmentLog,NaN
2,b1_113,Appraise property,2004/02/11 17:58:18.693,2004/02/11 17:58:18.693,MXML.EnactmentLog,NaN
3,b1_113,Check credit history,2004/02/11 18:12:06.935,2004/02/11 18:12:06.935,MXML.EnactmentLog,NaN
4,b1_113,Assess loan risk,2004/02/11 19:22:58.531,2004/02/11 19:22:58.531,MXML.EnactmentLog,NaN
5,b1_113,Assess eligibility,2004/02/11 19:30:07.055,2004/02/11 19:30:07.055,MXML.EnactmentLog,NaN