In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/meruozhu/Downloads/MP_data/MP_codes/MP/Data/sudden_drift/BPIC17.csv')

In [3]:
df.columns

Index(['Action', 'role', 'concept:name', 'EventOrigin', 'eventID',
       'lifecycle:transition', 'completeTime', 'case:LoanGoal',
       'case:ApplicationType', 'case', 'case:RequestedAmount',
       'FirstWithdrawalAmount', 'NumberOfTerms', 'Accepted', 'MonthlyCost',
       'Selected', 'CreditScore', 'OfferedAmount', 'OfferID', 'event'],
      dtype='object')

In [4]:
df['case']=df['case:concept:name']

In [5]:
df['event']=df['concept:name']

In [6]:
df['completeTime']=df['time:timestamp']

### change complete time format

In [7]:
df['completeTime']=pd.to_datetime(df['completeTime']).dt.strftime('%Y-%m-%d %H:%M:%S+00:00')

In [8]:
df

,Action,role,concept:name,EventOrigin,eventID,lifecycle:transition,completeTime,case:LoanGoal,case:ApplicationType,case,case:RequestedAmount,FirstWithdrawalAmount,NumberOfTerms,Accepted,MonthlyCost,Selected,CreditScore,OfferedAmount,OfferID,event
0,Created,User_1,A_Create Application,Application,Application_652823628,complete,2016-01-01 09:51:15+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CreatedA_Create Application
1,statechange,User_1,A_Submitted,Application,ApplState_1582051990,complete,2016-01-01 09:51:15+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,statechangeA_Submitted
2,Created,User_1,W_Handle leads,Workflow,Workitem_1298499574,schedule,2016-01-01 09:51:15+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CreatedW_Handle leads
3,Deleted,User_1,W_Handle leads,Workflow,Workitem_1673366067,withdraw,2016-01-01 09:52:36+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DeletedW_Handle leads
4,Created,User_1,W_Complete application,Workflow,Workitem_1493664571,schedule,2016-01-01 09:52:36+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CreatedW_Complete application
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,statechange,User_87,O_Accepted,Offer,OfferState_1328381608,complete,2016-03-16 07:08:36+00:00,Car,Limit raise,Application_708091569,75000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Offer_1447615996,statechangeO_Accepted
199996,statechange,User_87,A_Pending,Application,ApplState_1899280229,complete,2016-03-16 07:08:36+00:00,Car,Limit raise,Application_708091569,75000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,statechangeA_Pending
199997,Deleted,User_87,W_Validate application,Workflow,Workitem_1342131678,complete,2016-03-16 07:08:36+00:00,Car,Limit raise,Application_708091569,75000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DeletedW_Validate application
199998,Created,User_28,A_Create Application,Application,Application_1647390747,complete,2016-03-07 19:50:43+00:00,Car,New credit,Application_1647390747,26000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CreatedA_Create Application
199999,Created,User_28,W_Complete application,Workflow,Workitem_921821777,schedule,2016-03-07 19:50:43+00:00,Car,New credit,Application_1647390747,26000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CreatedW_Complete application

In [9]:
df.to_csv('/Users/meruozhu/Downloads/MP_data/MP_codes/MP/Data/sudden_drift/BPIC17_new.csv')